clientRequestUrl:
  - https://rpc.ankr.com/polygon
clientRequestSpecialUrl:
jobRequestUrl:
jobRequestSpecialUrl:
specialMethods:

#logPath: /path/to/log
loopSeconds: 1
cacheSeconds: 60
backendHttpSeconds: 10
frontHttpSeconds: 22
channelSize: 120
pullJobSize: 100
chain: 137
port: 9991